# Generated by Django 5.2 on 2025-04-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
